# Generated by Django 3.2.9 on 2022-04-22 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='отправлено')),
            ],
            options={
                'verbose_name': 'диалог',
                'verbose_name_plural': 'диалоги',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DialogMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('0', 'создатель'), ('1', 'собеседник')], db_index=True, max_length=64, verbose_name='роль')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chatapp.dialog', verbose_name='диалог')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to=settings.AUTH_USER_MODEL, verbose_name='участник диалога')),
            ],
            options={
                'ordering': ['dialog', '-role', 'member'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='сообщение')),
                ('read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='отправлено')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatapp.dialogmembers', verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['-created'],
            },
        ),
    ]
